### ISSUE TITLE
Pro import is missing

### ISSUE THREAD

**Issue by brupelo** [dpistelli/xptmrt#1]
@dpistelli Hi there! I'd really like to test your repository, haven't cloned yet but I don't see the `Pro` import available... Is that module living on Pypi? Haven't found it there neither...

Thanks in advance :) 

PS. I'm the guy who asked some questions about your [impressive article](https://ntcore.com/?p=458) few minutes ago

**Comment by epistelli** [comment]
Hey BPL, thanks again :) I answered the questions on the blog. Hope this helps!
